function [respath] = generateWalkerParts()

    conditions = diag(Inf(11, 1));
% [ [Inf zeros(1, 10)]; ...
%         [zeros(1, 1) Inf zeros(1, 9)]; ...
%         [zeros(1, 2) Inf zeros(1, 8)]; ...
%         [zeros(1, 3) Inf zeros(1, 7)]; ...
%         [zeros(1, 4) Inf zeros(1, 6)]; ...
%         [zeros(1, 5) Inf zeros(1, 5)]; ...
%         [zeros(1, 6) Inf zeros(1, 4)]; ...        
%         [zeros(1, 7) Inf zeros(1, 3)]; ...
%         [zeros(1, 8) Inf zeros(1, 2)]; ...        
%         [zeros(1, 9) Inf zeros(1, 1)]; ...
%         [zeros(1, 10) Inf]]; 

    conditionnames = {'elem_leftUpperarm', ... 
        'elem_rightUpperarm', ...
        'elem_leftThigh', ...
        'elem_rightThigh', ...
        'elem_rightLeg', ...
        'elem_leftLeg', ...
        'elem_leftForearm', ...
        'elem_rightForearm', ...
        'elem_lowerBody', ...
        'elem_midBody', ...
        'elem_head'};
    
    %walking angle [3 * pi/2 0] is for AWAY direction
    %light angle 18*pi/16 is above for AWAY walker
    %light angle -2*pi/16 is below for AWAY walker
    
    %walking angle [pi/2 0] is for TOWARDS direction
    %light angle 14*pi/16 is above for TOWARDS walker
    %light angle 2*pi/16 is below for TOWARDS walker

    for i = 1 : size(conditionnames, 2),
        conditionnames{i}
        generateWalker('StNW1', 2 * pi / 16, [pi/2 0], [0.0 0.0 0.0], [900 900], ...
            conditionnames{i}, inf(1, 9), conditions(i, :), [0 0], [1 1 1 1 1])
    end